2nd commit

diff --git a/10-install-mysql-sh b/10-install-mysql-sh
--- a/10-install-mysql-sh
+++ b/10-install-mysql-sh
@@ -8,12 +8,24 @@
 # Install mysql, If success - Guve Success message "- The Installation is successful"
 # If not throw an error "- The installation is Failed"
 
+# We need to use EXIt status here to check if the command is not successful the next command should run and shell script should be stopped.
+# "$?" is the command to check the EXIT status, If it is "0" - Success, Othen than 0 --> Failed
+
 ID=$(id -u)
 if [ $ID -ne 0 ]
 then
     echo "ERROR: You do not have root permission to run this command"
+    exit 1 # This is the exit command status, shell script will not run if exit status is not "0".
 else
-    echo "You are root user"
+    echo "You are a root user"
 fi
 
 yum install mysql -y
+
+if [ $? -ne 0 ]
+then
+    echo " Installation of mysql failed"
+    exit 1
+else
+    echo "Installation of mysql is successful."
+fi
