5th commit

diff --git a/10-install-mysql-sh b/10-install-mysql-sh
--- a/10-install-mysql-sh
+++ b/10-install-mysql-sh
@@ -29,3 +29,14 @@ then
 else
     echo "Installation of mysql is successful."
 fi
+
+yum install git -y
+
+if [ $? -ne 0 ]
+then
+    echo " Installation of git failed"
+    exit 1
+else
+    echo "Installation of git is successful."
+fi
+
